name: Server Deploy

on:
  push:
    branches:
      - 'main'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # 'deploy' is a unique identifier for your job
  Upload_image:
    name: Upload image on Dockerhub
    runs-on: ubuntu-latest
    steps:
      # check the code using github checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push Docker image
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t z623nd3/chatbotv0:latest .
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push z623nd3/chatbotv0:latest
  Deploy:
    name: Deploy servers
    runs-on: ubuntu-latest
    steps:
      # deploy our app on cloud server
      - run: echo deploying

# maybe you need to import the Server API TOKEN to Github ENV
# And you can learn how to do from our Lab6
# env:



